DELIMITER = '-'

# OPERATION
LOGIN_PROTOCOL = 'login'
MATCH_PROTOCOL = 'match'
GAME_START_PROTOCOL = 'start'
CHECK_USER_IDENTITY_PROTOCOL = 'check'
GAME_INIT_PROTOCOL = 'init'

# STATUS
STATUS_NAME = ['成功', '服务器错误', '禁止访问', '用户名或密码错误']
STATUS_ALL = ['200', '300', '400', '401']
OK = 0
ERROR = 1
FORBIDDEN = 2
USERNAME_PASSWORD_WRONG = 3

